notifications:
  email:
    on_success: never
    on_failure: change

branches:
   only:
     - gh-pages

language: python
python:
  - "2.7"

install: "pip install -r requirements.txt"

script:
  - "bash ./scripts/deploy.sh"

env:
  global:
  - ENCRYPTION_LABEL: "03cc74286256"
  - COMMIT_AUTHOR_EMAIL: "jan.garaj@gmail.com"
